### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by DocMAX** [sahlberg/pop-fe#12]
What's the problem here?
```
Converting TRACK_2_02.wav to TRACK_2_02.aea
0 132300
WARNING: ATRAC3 is uncompleted, result will be not good )))
bitrate 132300
\  99% done
Done
Try URL http://www.hwc.nat.cu/psx/SLUS_012.01_COV.jpg
Id: SLUS01201
Title: ALONE IN THE DARK - THE NEW NIGHTMARE
/home/docmax/github/pop-fe/./pop-fe.py:542: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  image = icon0.resize((80,80), Image.BILINEAR)
/home/docmax/github/pop-fe/./pop-fe.py:549: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  pic1 = pic1.resize((480, 272), Image.BILINEAR).convert("RGBA")
Traceback (most recent call last):
  File "/home/docmax/github/pop-fe/./pop-fe.py", line 1589, in <module>
    create_psp(args.psp_dir, game_id, game_title, icon0, pic1, cue_files, cu2_files, img_files, mem_cards, aea_files, snd0=snd0)
  File "/home/docmax/github/pop-fe/./pop-fe.py", line 550, in create_psp
    pic1 = add_image_text(pic1, game_title, game_id)
  File "/home/docmax/github/pop-fe/./pop-fe.py", line 275, in add_image_text
    fnt = ImageFont.truetype(font, 20)
  File "/usr/lib/python3.10/site-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/lib/python3.10/site-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/lib/python3.10/site-packages/PIL/ImageFont.py", line 247, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by DocMAX** [comment]
OK fixed on arch linux: yay -s dejavu

**Comment by sahlberg** [comment]
Is this something that should be added to the README ?

**Comment by DocMAX** [comment]
I think so, this is not mentioned there.
