### ISSUE TITLE
Error making EBOOT

### ISSUE THREAD

**Issue by DocMAX** [sahlberg/pop-fe#13]
Path /mnt/zeus/8bay_usb3/roms/ps1/test_pbp/PSP/PSP/GAME exists!
```
Try URL http://www.hwc.nat.cu/psx/SLUS_012.01_COV.jpg
Id: SLUS01201
Title: ALONE IN THE DARK - THE NEW NIGHTMARE
/home/docmax/github/pop-fe/./pop-fe.py:542: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  image = icon0.resize((80,80), Image.BILINEAR)
/home/docmax/github/pop-fe/./pop-fe.py:549: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  pic1 = pic1.resize((480, 272), Image.BILINEAR).convert("RGBA")
/home/docmax/github/pop-fe/./pop-fe.py:280: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  ts = d.textsize(t, font=fnt)
/home/docmax/github/pop-fe/./pop-fe.py:280: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  ts = d.textsize(t, font=fnt)
/home/docmax/github/pop-fe/./pop-fe.py:287: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  ts = d.textsize(game_id, font=fnt)
Create PBP file at /mnt/zeus/8bay_usb3/roms/ps1/test_pbp/PSP/GAME/SLUS01201/EBOOT.PBP
Traceback (most recent call last):
  File "/home/docmax/github/pop-fe/./pop-fe.py", line 1589, in <module>
    create_psp(args.psp_dir, game_id, game_title, icon0, pic1, cue_files, cu2_files, img_files, mem_cards, aea_files, snd0=snd0)
  File "/home/docmax/github/pop-fe/./pop-fe.py", line 593, in create_psp
    generate_pbp(dest_file, game_id, game_title, icon0, pic1, cue_files, cu2_files, img_files, aea_files, snd0=snd0_data)
  File "/home/docmax/github/pop-fe/./pop-fe.py", line 531, in generate_pbp
    p.create_pbp()
  File "/home/docmax/github/pop-fe/popstation.py", line 3006, in create_pbp
    fh = open(self._eboot, 'wb+')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/zeus/8bay_usb3/roms/ps1/test_pbp/PSP/GAME/SLUS01201/EBOOT.PBP'

```

**Comment by DocMAX** [comment]
One again, stupid mistake of mine - dir did NOT exist...

**Comment by KleversonKrash** [comment]
How to solve ?

**Comment by VoidAlone** [comment]
Sorry to necro this, but are we expected to make the subdirs for every game we convert? Does it not use makedirs? I'm not sure how anyone is using this if they have to look up the identifier for each game and manually make the dir beforehand

**Comment by sahlberg** [comment]
The directories PSP/GAME/ must already exist, then pop-fe will create the subdirectoy witidentifier and put the eboot in it.

The whole idea is that you connect you PSP as a usb device to your computer, then set the output directory to the root of the drive that the PSP shows up at.
Then when you create the eboot it will automatically be put in Z:/PSP/GAME/identifier/EBOOT.PBP and you don't have to copy the files yourself.

**Comment by VoidAlone** [comment]
Hmmm weird. I definitely have the PSP/GAME directories, but it wouldn't create the subdirs for the games. I had to add a line to do makedirs in the create_pbp. Not sure what the problem was. 

Also, didn't mean to sound rude or anything. I'm rereading my comment and see it might have come across that way. My bad!
