### ISSUE TITLE
Crashes on STAR WARS - EPISODE I - THE PHANTOM MENACE

### ISSUE THREAD

**Issue by MediaMaquina** [sahlberg/pop-fe#168]
```
ID SLUS00884
Found an external config for SLUS00884
Found cached prebuilt PIC0 https://github.com/sahlberg/pop-fe-assets/raw/master/pic0/f49ab1f2baa5c86eab2ef6ef389a88c7
Found cached prebuilt PIC1 https://github.com/sahlberg/pop-fe-assets/raw/master/pic1/1fcd0724e6a07f0617db2523e559b983
Creating EBOOT
DISC SLUS00884
TITLE STAR WARS - EPISODE I - THE PHANTOM MENACE
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 565, in on_create_eboot
  File "pop-fe.py", line 2104, in apply_ppf_fixes
UnboundLocalError: local variable 'ppf' referenced before assignment
```

**Comment by sahlberg** [comment]
This should be fixed in this build:
https://github.com/sahlberg/pop-fe/actions/runs/8621626744
