### ISSUE TITLE
16 Tales 2 fails to convert

### ISSUE THREAD

**Issue by billtookahit420** [sahlberg/pop-fe#65]
when selecting 16 tales 2 cue file this is what pops up for an error

cdrom: line in system.cnf does not contain a proper id, read disc label instead
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-ps3.py", line 426, in on_path_changed
  File "pop-fe-ps3.py", line 258, in update_assets
  File "pop-fe.py", line 177, in get_game_from_gamelist
KeyError: 'LSP-99012'

**Comment by sahlberg** [comment]
Try this when the build finishes:
https://github.com/sahlberg/pop-fe/actions/runs/6998733917

16 Tales had an unusual format of the system.cnf file but I have added handling of it now.
Unfortunately I could not find any good images for PIC1 :-(

**Comment by billtookahit420** [comment]
thank you for fixing this, keep up the awesome work this program is amazing.
