### ISSUE TITLE
Can't convert Overblood (SLUS-00464)

### ISSUE THREAD

**Issue by Webardo** [sahlberg/pop-fe#68]
An exception occurs due to pic 0.

ID SLUS00464
Fetching SND0
Found cached prebuilt PIC0 https://github.com/sahlberg/pop-fe-assets/raw/master/pic0/b2c05932bce8e0bf9800b1c42d16ecfa
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 377, in on_path_changed
  File "pop-fe-psp.py", line 245, in update_assets
  File "pop-fe.py", line 395, in get_pic0_from_game
  File "PIL\Image.py", line 2939, in new
TypeError: color must be int, or tuple of one or two elements

**Comment by sahlberg** [comment]
Fixed. PIL did not like that image so I changed the get_pic0_from... parser to catch the exception and just ignore the image if it is broken.
I also swapped the pic0 logo to a different one that PIL can parse.

should work now.

**Comment by Webardo** [comment]
Works perfectly now, thank you very much.
