### ISSUE TITLE
Demo Discs not recognised

### ISSUE THREAD

**Issue by Desz5** [sahlberg/pop-fe#72]
When creating pkg's with the following serials: SCED01152, SCED01819.... Everything with SCEDxxxxx.
Pop-fe doesn't recognises the demodiscs and won't allow to create a PKG resulting with the following error:

MD5 fingerprint 3666db2627089e419f6702b1e5eea955
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-ps3.py", line 427, in on_path_changed
  File "pop-fe-ps3.py", line 259, in update_assets
  File "pop-fe.py", line 212, in get_game_from_gamelist
KeyError: 'SCED01152'

**Comment by sahlberg** [comment]
I have added database entries for all the demo discs on this page:
https://crimson-ceremony.net/demopals/ps1-master.php

For now, the entries only contain the disc-id and the name of the disc. No icon0/pic0/pic1  but that can be added later.
At least pop-fe will recognize all these disks now.

Not sure what to use for the images.   Maybe use the cover of the magazine that they were distributed with as PIC1 ?
I am not going to add these   but if you have ideas and want to add some links to icon0/pic0/pic1 assets, please send a pull request.

**Comment by sahlberg** [comment]
Hi, I have added assets for all 108 Official Playstation UK Magazine cover disks.
Are there other sets you want added too?

**Comment by VirulentSlayer** [comment]
Demo One (Version 6) is not grabbing anything, thus no pkg can be made with pop-f3-ps3

[INFO]  Opening cue: \\(1994) psx\Undithered\Demo One (Version 6) (Europe, Australia) (En,Fr,De,Es,It)\Demo One (Version 6) (Europe, Australia) (En,Fr,De,Es,It).cue
[INFO]  Merging 2 tracks...
[INFO]  Wrote D:\psx pop fe\pop-fe-ps3-work\MB1.bin
[INFO]  Wrote new cue: D:\psx pop fe\pop-fe-ps3-work\MB1.cue
MD5 fingerprint 5a1680570d4961ee3b75eff78f3ab696
Exception in Tkinter callback
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\connectionpool.py", line 534, in _make_request
  File "urllib3\connection.py", line 571, in getresponse
  File "http\client.py", line 1377, in getresponse
  File "http\client.py", line 320, in begin
  File "http\client.py", line 289, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 644, in send
  File "urllib3\connectionpool.py", line 841, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\connectionpool.py", line 534, in _make_request
  File "urllib3\connection.py", line 571, in getresponse
  File "http\client.py", line 1377, in getresponse
  File "http\client.py", line 320, in begin
  File "http\client.py", line 289, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-ps3.py", line 454, in on_path_changed
  File "pop-fe-ps3.py", line 386, in update_assets
  File "popfe.py", line 2112, in get_icon0_from_game
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 659, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by sahlberg** [comment]
Can you try the latest build if it still happens:

https://github.com/sahlberg/pop-fe/actions/runs/30789448547

**Comment by VirulentSlayer** [comment]
pop-fe-ps3 from v1.26 pop-fe-ui? 

[INFO]  Output directory: C:\pop-fe-ui\pop-fe-ps3-work
[INFO]  Opening cue: \\(1994) psx\Undithered\Demo One (Version 6) (Europe, Australia) (En,Fr,De,Es,It)\Demo One (Version 6) (Europe, Australia) (En,Fr,De,Es,It).cue
[INFO]  Merging 2 tracks...
[INFO]  Wrote C:\pop-fe-ui\pop-fe-ps3-work\MB1.bin
[INFO]  Wrote new cue: C:\pop-fe-ui\pop-fe-ps3-work\MB1.cue
MD5 fingerprint 5a1680570d4961ee3b75eff78f3ab696
Exception in Tkinter callback
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\connectionpool.py", line 534, in _make_request
  File "urllib3\connection.py", line 571, in getresponse
  File "http\client.py", line 1377, in getresponse
  File "http\client.py", line 320, in begin
  File "http\client.py", line 289, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 644, in send
  File "urllib3\connectionpool.py", line 841, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\connectionpool.py", line 534, in _make_request
  File "urllib3\connection.py", line 571, in getresponse
  File "http\client.py", line 1377, in getresponse
  File "http\client.py", line 320, in begin
  File "http\client.py", line 289, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-ps3.py", line 454, in on_path_changed
  File "pop-fe-ps3.py", line 386, in update_assets
  File "popfe.py", line 2112, in get_icon0_from_game
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 659, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

No joy

**Comment by sahlberg** [comment]
No, not 1.26,  the one at the bottom of this page :
https://github.com/sahlberg/pop-fe/actions/runs/30789448547

**Comment by VirulentSlayer** [comment]
ok, sorry about that, yes i can confirm this still has a problem.

 [INFO]  Output directory: C:\pop-fe\pop-fe-ps3-work
[INFO]  Opening cue: \\(1994) psx\Undithered\Demo One (Version 6) (Europe, Australia) (En,Fr,De,Es,It)\Demo One (Version 6) (Europe, Australia) (En,Fr,De,Es,It).cue
[INFO]  Merging 2 tracks...
[INFO]  Wrote C:\pop-fe\pop-fe-ps3-work\MB1.bin
[INFO]  Wrote new cue: C:\pop-fe\pop-fe-ps3-work\MB1.cue
MD5 FINGERPRINT cff5fc532e09d2d3c89c1719c5ee77a3 PBPX95007
Exception in Tkinter callback
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\connectionpool.py", line 534, in _make_request
  File "urllib3\connection.py", line 571, in getresponse
  File "http\client.py", line 1377, in getresponse
  File "http\client.py", line 320, in begin
  File "http\client.py", line 289, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 644, in send
  File "urllib3\connectionpool.py", line 841, in urlopen
  File "urllib3\util\retry.py", line 490, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\connectionpool.py", line 534, in _make_request
  File "urllib3\connection.py", line 571, in getresponse
  File "http\client.py", line 1377, in getresponse
  File "http\client.py", line 320, in begin
  File "http\client.py", line 289, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-ps3.py", line 467, in on_path_changed
  File "pop-fe-ps3.py", line 397, in update_assets
  File "popfe.py", line 2113, in get_icon0_from_game
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 659, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by VirulentSlayer** [comment]
It's PBPX95007 specifically, 
I have had no issues with other titles, 91 titles packaged no problems.

**Comment by sahlberg** [comment]
I found the issue.  The icon0 file can no longer be downloaded from the original site and this caused the crash.

Try the version here, it works:
https://github.com/sahlberg/pop-fe/actions/runs/30846740026

**Comment by VirulentSlayer** [comment]
You got it, excellent. No more errors. Thank you so much!
